// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.monitor.domain;

import org.seforge.monitor.domain.ResourcePropertyKey;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ResourcePropertyKey_Roo_Configurable {
    
    declare @type: ResourcePropertyKey: @Configurable;
    
}
